jwt-const:
  issuer: green@green.kr
  secret: bwrahkgtfjhewsghjvbhjavfhyjaeswgjbeshjabhjewbvnmbdhjtgfvrehjbmfnxdzbhjlgnb
  header-schema-name: Authorization
  claim-key: signedUser
  token-name: jwt
  token-type: Bearer
  access-token-expiry: 600_000 # 10분 (MS)
  refresh-token-expiry: 1_296_000_000 # 15일 (MS)
  refresh-token-cookie-name: refresh-token
  refresh-token-cookie-expiry: 1_296_000 # 15일 (S)

const:
  default-page-size: 20
file:
  directory: D:\2024-02

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: studyBridge
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/acamatch
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: 0ca2sa0@gmail.com
    password: wotrvbcpartvbbmk
    properties:
      mail:
        smtp:
          auth: true  # SMTP 인증 사용
          starttls:
            enable: true

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
  cache:
    disabled: true